// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABYjg9mX5Lx9fRxUaUpThZEuOekR2VeXg',
    appId: '1:722656224547:web:4df909b4a244c5c5375896',
    messagingSenderId: '722656224547',
    projectId: 'smart-ticketing-flutter',
    authDomain: 'smart-ticketing-flutter.firebaseapp.com',
    storageBucket: 'smart-ticketing-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPGgdH_2wHHR1RcJeq3tgcDNYsCJBCHaU',
    appId: '1:722656224547:android:d4df8e06e2f0d88f375896',
    messagingSenderId: '722656224547',
    projectId: 'smart-ticketing-flutter',
    storageBucket: 'smart-ticketing-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhgzC4cWwsOae7sMlWfXp7jU4mSSQepaI',
    appId: '1:722656224547:ios:d51e462672060ebc375896',
    messagingSenderId: '722656224547',
    projectId: 'smart-ticketing-flutter',
    storageBucket: 'smart-ticketing-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhgzC4cWwsOae7sMlWfXp7jU4mSSQepaI',
    appId: '1:722656224547:ios:d51e462672060ebc375896',
    messagingSenderId: '722656224547',
    projectId: 'smart-ticketing-flutter',
    storageBucket: 'smart-ticketing-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABYjg9mX5Lx9fRxUaUpThZEuOekR2VeXg',
    appId: '1:722656224547:web:dba0f5b65efebd8b375896',
    messagingSenderId: '722656224547',
    projectId: 'smart-ticketing-flutter',
    authDomain: 'smart-ticketing-flutter.firebaseapp.com',
    storageBucket: 'smart-ticketing-flutter.firebasestorage.app',
  );
}
